<?php


namespace Nemundo\App\Scheduler\Page;


use Nemundo\App\Application\Com\ApplicationListBox;
use Nemundo\App\Scheduler\Com\Table\SchedulerTable;
use Nemundo\App\Scheduler\Template\SchedulerTemplate;
use Nemundo\Com\FormBuilder\SearchForm;
use Nemundo\Package\Bootstrap\Form\BootstrapFormRow;

class SchedulerPage extends SchedulerTemplate
{

    public function getContent()
    {

        $form = new SearchForm($this);

        $formRow = new BootstrapFormRow($form);

        $application = new ApplicationListBox($formRow);
        $application->submitOnChange = true;
        $application->value = $application->getValue();

        $table = new SchedulerTable($this);
        $table->applicationId = $application->getValue();

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}