<?php


namespace Nemundo\App\Scheduler\Template;


use Nemundo\Com\Template\AbstractTemplateDocument;

class SchedulerTemplate extends AbstractTemplateDocument
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub
    }

}