<?php

namespace Nemundo\Admin\Com\ListBox;

class AdminTextBox extends AbstractAdminTextBox
{


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub



    }

    public function getContent()
    {

        $this->textInput->addCssClass('admin-input');
        $this->textInput->autocomplete = false;
        return parent::getContent();

    }

}