<?php


namespace Nemundo\App\Application;


use Nemundo\Com\Template\AbstractTemplateDocument;

class ApplicationPage extends AbstractTemplateDocument
{

    public function getContent()
    {



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}