<?php

namespace Nemundo\Admin\SqlAnalyzer;


use Nemundo\Db\Connection\AbstractConnection;

class SqlAnaylzerConnection extends AbstractConnection
{

    protected function loadConnection()
    {
        parent::loadConnection(); // TODO: Change the autogenerated stub
    }

    public function connect()
    {
        // TODO: Implement connect() method.
    }

}