<?php


namespace Nemundo\App\Translation\Com\Form;


use Nemundo\Admin\Com\Form\AbstractAdminEditForm;

use Nemundo\App\Translation\Com\Container\TranslationFormContainer;
use Nemundo\App\Translation\Data\Source\SourceReader;
use Nemundo\App\Translation\Type\Source\SourceType;
use Nemundo\App\Translation\Type\Source\TextSourceType;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class TranslationForm extends BootstrapForm
{

    public $sourceId;


    /**
     * @var TranslationFormContainer
     */
    private $container;


    public function getContent()
    {


        $sourceReader = new SourceReader();
        $sourceReader->model->loadSourceType();
        $sourceRow= $sourceReader->getRowById($this->sourceId);

        $sourceType = new SourceType();
        $sourceType->sourceType = $sourceRow->sourceType->sourceType;

        $this->container=new TranslationFormContainer($this);
        $this->container->sourceType =$sourceType;
        $this->container->source = $sourceRow->source;

        /*
        $translationRow=(new TranslationReader())->getRowById($this->translationId);


        $this->text=new BootstrapTextBox($this);
        $this->text->label='Text';
        $this->text->value=$translationRow->text;*/

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


protected function onSubmit()
{


    $sourceRow=(new SourceReader())->getRowById($this->sourceId);

//    $this->container->saveTranslation($this->sourceId);
    $this->container->saveTranslation($sourceRow->source);


    /*
    $update=new TranslationUpdate();
    $update->text=$this->text->getValue();
    $update->updateById($this->translationId);*/

}


}