<?php


namespace Nemundo\App\Linux\Cmd;


class UserToGroupCmd extends AbstractCmd
{

    public $user;

    public $group;

    public function getCommandList()
    {

        $this->addCommandLine('usermod -a -G '.$this->group.' '.$this->user);

        return parent::getCommandList(); // TODO: Change the autogenerated stub
    }

}