<?php

namespace Nemundo\Admin\Com\Card;

use Nemundo\Html\Block\Div;

class AdminCardContainer extends Div
{

    public function getContent()
    {

        $this->addCssClass('admin-card-container');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}