<?php

namespace Nemundo\Admin\Com\Navbar;

use Nemundo\Com\Html\Hyperlink\SiteHyperlink;

class AdminSubmenuSiteHyperlink extends SiteHyperlink
{

    public function getContent()
    {

        //$this->addCssClass('admin-navbar-link');
        $this->addCssClass('admin-navbar-submenu-link');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}