<?php

namespace Nemundo\Admin\Com\Image;

use Nemundo\Package\CropperJs\CropperJs;

class AdminCroppingImage extends CropperJs
{


    public function getContent()
    {



        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}