<?php

namespace Nemundo\Package\Echarts\Chart;


use Nemundo\Package\Echarts\Data\AbstractChartData;
use Nemundo\Package\Echarts\Data\LineChartData;

class PieEchart extends AbstractEchart
{

    public function __construct($parentContainer = null)
    {

        parent::__construct($parentContainer);

        $this->script = '
        series : [
        {
            name: "Reference Page",
            type: "pie",
            radius: "80px",
            data:[';


    }


    public function addData(AbstractChartData $chartData)
    {
        // TODO: Implement addData() method.
    }


    public function addValue($name, $value)
    {

        $this->script .= '{value:' . $value . ', name:"' . $name . '"},';
        return $this;

    }


    public function getContent()
    {


        $this->script .= ']
        }
],
';

 /*       $script->addScript('
        series : [
        {
            name: "Reference Page",
            type: "pie",
            radius: "100%",
            data:[
                {value:400, name:"Searching Engine"},
                {value:335, name:"Direct"},
                {value:310, name:"Email"},
                {value:274, name:"Alliance Advertisement"},
                {value:235, name:"Video Advertisement"}
            ]
        }
    ],
    ');*/


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}