<?php

namespace Nemundo\Com\Video\Vimeo;


use Nemundo\Html\Iframe\Iframe;
use Nemundo\Com\Video\AbstractVideoPlayer;

class VimeoPlayer extends AbstractVideoPlayer
{


    public function getContent()
    {

        //<iframe src="https://player.vimeo.com/video/31243487" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

        $url = 'https://player.vimeo.com/video/' . $this->videoId;

        //  $url->addParameterValue('autoplay', '1');
        //  $url->addParameterValue('showinfo', '0');


        $iframe = new Iframe($this);
        $iframe->width = $this->width;
        $iframe->height = $this->height;
        $iframe->src = $url;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}