<?php

namespace Nemundo\App\Application\Reader;

use Nemundo\App\Application\Data\Project\ProjectReader;

class ProjectDataReader extends ProjectReader
{

    public function getData()
    {

        $this->addOrder($this->model->project);

        return parent::getData(); // TODO: Change the autogenerated stub
    }

}