<?php


namespace Nemundo\App\Apache\Cmd;


use Nemundo\App\Linux\Cmd\AbstractCmd;

class ApacheRestartCmd extends AbstractCmd
{

    public function getCommandList()
    {

        $this->addCommandLine('service apache2 restart');

        return parent::getCommandList(); // TODO: Change the autogenerated stub
    }

}