<?php

namespace Nemundo\User\Reader\User;

use Nemundo\User\Data\User\UserReader;

class UserDataReader extends UserReader
{

    // onlyActive


    // getUsergroup

    public function getData()
    {

        $this->filter->andEqual($this->model->active, true);
        $this->addOrder($this->model->displayName);


        return parent::getData(); // TODO: Change the autogenerated stub
    }

}