<?php

namespace Nemundo\App\System\Page;


use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\App\System\Com\SystemInformationTable;
use Nemundo\App\System\Com\Table\MySqlSystemTable;
use Nemundo\App\System\Com\Table\PhpSystemTable;
use Nemundo\App\System\Com\Table\SystemTable;
use Nemundo\Com\Template\AbstractTemplateDocument;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;

class SystemPage extends AbstractTemplateDocument
{

    public function getContent()
    {


        $layout = new BootstrapTwoColumnLayout($this);

        $widget=new AdminWidget($layout->col1);
        $widget->widgetTitle='System';
        new SystemTable($widget);

        $widget=new AdminWidget($layout->col1);
        $widget->widgetTitle='PHP';
        new PhpSystemTable($widget);

        $widget=new AdminWidget($layout->col1);
        $widget->widgetTitle='MySql';
        new MySqlSystemTable($widget);



        new SystemInformationTable($layout->col2);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}