<?php

namespace Nemundo\Package\Bootstrap\Navbar;


use Nemundo\Com\FormBuilder\SearchForm;

class BootstrapNavbarSearchForm extends SearchForm
{


    public function getContent()
    {

        $this->addCssClass('d-flex');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    /*
<form class="d-flex">
<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
<button class="btn btn-outline-success" type="submit">Search</button>
</form>*/


}