<?php


namespace Nemundo\Package\Bootstrap\Navbar;


use Nemundo\Html\Hyperlink\AbstractHyperlink;

class BootstrapNavbarBrand extends AbstractHyperlink
{

    public function getContent()
    {

        $this->addCssClass('navbar-brand');
        $this->href='#';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    // <a class="navbar-brand" href="#">Navbar</a>


}