<?php

namespace Nemundo\Package\OpenLayers\Com;

use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Html\Header\Link\StylesheetLink;
use Nemundo\Html\Script\JavaScript;

class OpenLayersHeaderPackage extends AbstractHtmlContainer
{

    public function getContent()
    {

        //$this->addCssUrl('/asset/open_layers/ol.css');

        $stylesheet=new StylesheetLink($this);
        $stylesheet->href = '/asset/open_layers/ol.css';

        $ol = new JavaScript($this);
        $ol->src='/asset/open_layers/ol.js';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}