<?php

namespace Nemundo\Web\Parameter;


use Nemundo\Core\Log\LogMessage;

abstract class AbstractMultipleUrlParameter extends AbstractUrlParameter
{

    public $parameterName;

    private $valueList = [];


    public function __construct($valueList = [])
    {

        if (!is_array($valueList)) {
            (new LogMessage())->writeError('AbstractMultpleUrlParameter: No valid Array');
        }

        parent::__construct();
        $this->valueList = $valueList;

    }


    public function addValue($value)
    {

        $this->valueList[] = $value;
        return $this;

    }


    // getValueList
    // getValue
    public function getMulipleValue()
    {

        $list = $this->valueList;
        if (isset($_REQUEST[$this->parameterName])) {
            foreach ($_REQUEST[$this->parameterName] as $value) {
                $list[] = trim($value);
            }
        }

        return $list;

    }


    public function hasValue()
    {

        $hasValue = true;
        if (isset($_REQUEST[$this->parameterName])) {


            foreach ($_REQUEST[$this->parameterName] as $value) {

                $value = trim($value);

                if (($value == '') || ($value == '0')) {
                    $hasValue = false;
                }


            }

        }

        return $hasValue;

    }

    public function getValue()
    {

        (new LogMessage())->writeError('GetValue. Not allowed.');
        //    return parent::getValue(); // TODO: Change the autogenerated stub
    }


    public function getUrl()
    {

        $urlList = [];
        foreach ($this->getMulipleValue() as $value) {
            $urlList[] = $this->parameterName . '[]=' . $value;
        }

        $url = '';
        if (sizeof($urlList) > 0) {
            $url = join('&', $urlList);
        }

        return $url;

    }


    public function getJson()
    {

        $json = json_encode($this->getMulipleValue());
        return $json;

    }

}