<?php


namespace Nemundo\Model\Path;


use Nemundo\Project\Path\LogPath;

class SetupLogPath extends LogPath
{

    protected function loadPath()
    {
        parent::loadPath(); // TODO: Change the autogenerated stub
        $this->addPath('setup');
        $this->addPath('table_setup.log');
    }

    /*
    public function __construct()
    {

        parent::__construct();
        $this->addPath('setup');
        $this->addPath('table_setup.log');

    }*/

}