<?php

namespace Nemundo\Admin\Com\Html;

use Nemundo\Com\Html\Listing\UnorderedList;

class AdminUnorderedList extends UnorderedList
{

    public function getContent()
    {

        $this->addCssClass('admin-bullet-list');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}