<?php

namespace Nemundo\App\Translation\Com\ListBox;

use Nemundo\App\Translation\Data\Language\LanguageReader;
use Nemundo\App\Translation\Data\SourceType\SourceTypeReader;
use Nemundo\App\Translation\Parameter\SourceTypeParameter;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;

class SourceTypeListBox extends BootstrapListBox
{


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->name=(new SourceTypeParameter())->getParameterName();
        $this->label = 'Source Type';

        $reader=new SourceTypeReader();
        $reader->addOrder($reader->model->sourceType);
        foreach ($reader->getData() as $sourceTypeRow) {
            $this->addItem($sourceTypeRow->id,$sourceTypeRow->sourceType);
        }

    }


    public function getContent()
    {



        return parent::getContent();
    }
}