<?php

namespace Nemundo\Admin\AppDesigner\Form\Index;


use Nemundo\Admin\AppDesigner\Data\AppModelIndexField\AppModelIndexFieldForm;
use Nemundo\Admin\AppDesigner\Orm\AppDesignerModelOrmSetup;

class ModelIndexFieldForm extends AppModelIndexFieldForm
{

    /**
     * @var string
     */
    public $modelId;

    /*
$form = new AppModelIndexFieldForm($layout->col1);
$form->connection = $conn;
$form->model->appIndexId->defaultValue = $indexId;
$form->model->appField->filter->andEqual((new AppModelFieldModel())->appModelId, $indexRow->appModelId);
$form->model->appField->filter->andEqual((new AppModelFieldModel())->active, true);
    //$form->model->action->addInsertAction(new AppModelIndexFieldAction());
$form->redirectSite = AppModelIndexSite::$site;
$form->redirectSite->addParameter($indexParameter);*/


    protected function onSubmit()
    {
        $value =  parent::onSubmit(); // TODO: Change the autogenerated stub



        $orm = new AppDesignerModelOrmSetup();
        $orm->connection = $this->connection;
        $orm->createOrm($this->modelId);


        return $value;


    }


}