<?php


namespace Nemundo\App\UserAction\Page;


use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\App\UserAction\Form\UserRegistrationForm;
use Nemundo\App\UserAction\Widget\LoginWidget;
use Nemundo\Com\Template\AbstractTemplateDocument;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;
use Nemundo\Web\Site\BaseUrlSite;

class LoginPage extends AbstractTemplateDocument
{

    public function getContent()
    {

        $layout=new BootstrapTwoColumnLayout($this);

        $widget=new LoginWidget($layout->col1);



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}