<?php

namespace Nemundo\Admin\Template;

use Nemundo\Admin\Com\Navbar\AdminNavbar;
use Nemundo\Package\Framework\FrameworkPackage;

class AssetAdminTemplate extends NavbarAdminTemplate
{


    protected function loadContainer()
    {
        AdminNavbar::$assetMode = true;
        $this->addPackage(new FrameworkPackage());

        parent::loadContainer();

    }


    public function getContent()
    {

        //$this->addPackage(new FrameworkPackage());

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}