<?php

namespace Nemundo\Admin\Template;

use Nemundo\Admin\Com\Navbar\AdminNavbar;
use Nemundo\Package\Framework\FrameworkPackage;

class AssetAdminTemplate extends NavbarAdminTemplate
{

    public function getContent()
    {

        AdminNavbar::$assetMode=true;

        $this->addPackage(new FrameworkPackage());

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}