<?php


namespace Nemundo\Admin\Com\Layout;


use Nemundo\Html\Block\Div;

class AdminRow extends Div
{

    public function getContent()
    {
        $this->addCssClass('nemundo-row');
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}