<?php

namespace Nemundo\App\ModelDesigner\Page\App;

use Nemundo\App\ModelDesigner\Com\Breadcrumb\ModelDesignerBreadcrumb;
use Nemundo\App\ModelDesigner\Com\Form\AppForm;
use Nemundo\App\ModelDesigner\Parameter\ProjectParameter;
use Nemundo\App\ModelDesigner\Site\App\AppNewSite;
use Nemundo\App\ModelDesigner\Site\AppSite;
use Nemundo\Com\Template\AbstractTemplateDocument;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;

class AppNewPage extends AbstractTemplateDocument
{

    public function getContent()
    {

        $project = (new ProjectParameter())->getProject();

        $breadcrumb = new ModelDesignerBreadcrumb($this);
        $breadcrumb->addProject($project);
        $breadcrumb->addActiveItem(AppNewSite::$site->title);

        $layout = new BootstrapTwoColumnLayout($this);

        $form = new AppForm($layout->col1);
        $form->project = $project;
        $form->redirectSite = AppSite::$site;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}