<?php

namespace Nemundo\Admin\Com\Form\File;

use Nemundo\Admin\Com\ListBox\AdminFileUpload;
use Nemundo\Html\Form\Input\AcceptFileType;

class AdminImageUpload extends AdminFileUpload
{

    public function getContent()
    {

        $this->acceptFileType=AcceptFileType::IMAGE;


        // bei edit



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}