<?php

namespace Nemundo\App\Scheduler\Com\Table;

use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Admin\Com\Table\AdminTableHeader;
use Nemundo\App\Scheduler\Data\Job\JobPaginationReader;
use Nemundo\App\Scheduler\Reader\JobDataReader;
use Nemundo\App\Scheduler\Status\FinishedSchedulerStatus;
use Nemundo\Com\TableBuilder\TableRow;

class JobTable extends AdminTable
{

    public $applicationId;

    public function getContent()
    {

        $jobReader = new JobDataReader();
        $jobReader->applicationId=$this->applicationId;

        //$table = new AdminTable($layout->col1);

        $header = new AdminTableHeader($this);
        $header->addText($jobReader->model->status->label);
        $header->addText($jobReader->model->script->label);
        $header->addText($jobReader->model->finished->label);
        $header->addText($jobReader->model->duration->label);

        foreach ($jobReader->getData() as $jobRow) {

            $row = new TableRow($this);
            $row->addText($jobRow->status->schedulerStatus);
            $row->addText($jobRow->script->scriptClass);
            $row->addYesNo($jobRow->finished);
            if ($jobRow->statusId == (new FinishedSchedulerStatus())->id) {
                $row->addText($jobRow->duration . ' sec');
            } else {
                $row->addEmpty();
            }

        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}